[package]
name = "uniswapv3_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
chrono = "0.4.26"
anyhow = "1.0.82"
thiserror = "1.0.65"
alloy = { version = "0.5.4", features = ["full"] }
